# Generated by Django 4.1.4 on 2022-12-12 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='Клиент', max_length=30, verbose_name='Роль')),
                ('surname', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('e_mail', models.CharField(blank=True, max_length=50, verbose_name='Почтовый адрес')),
                ('gender', models.CharField(blank=True, choices=[('М', 'мужчина'), ('Ж', 'женщина')], max_length=50, verbose_name='Пол')),
                ('DOR', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
                ('tag', models.CharField(blank=True, choices=[('Г', 'горячий'), ('П', 'постоянный'), ('В', 'вип'), ('С', 'скандальный'), ('Н', 'новый')], max_length=50, verbose_name='Тег')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
