# Generated by Django 4.1.4 on 2022-12-13 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Услуга')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(blank=True, verbose_name='Цена')),
                ('weight', models.PositiveIntegerField(blank=True, verbose_name='Вес')),
                ('size', models.PositiveIntegerField(blank=True, verbose_name='Обьем в см. куб.')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.productcategory', verbose_name='Категория')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.production', verbose_name='Производитель')),
            ],
        ),
    ]
